### ISSUE TITLE
Lips miss-synchronization 

### ISSUE THREAD

**Issue by amaroyo** [robotology/speech#15] opened 2017-05-05 15:13 UTC
Hello, 

I am currently using svox package to make iCub talk and I have notice three issues with the synchronization of the lips:

1) If you use short sentences like "Come stai?" After finishing the sentence, iCub keeps moving the lips for at least a couple of seconds more. 

2) If you put a text composed by 4-5 sentences, the lips begin moving but the actual sound doesn't start till 3-4 seconds later. 

3) If you introduce "..." to make a pause in the speech, iCub continues moving the lips. Fast example "Come ... stai?"

This creates an uncanny feeling if the people are watching the robot while talking.

Thanks, 
Alex.

**Comment by pattacini** [comment] 2017-05-05 15:44
Hi @amaroyo,

The relevant code responsible for synchronizing the lips movements and the utterance of the sentence can be browsed [here][1].

As you can see, `iSpeak` does 3 things in a row:
1. starts/resume the thread controlling the lips expressions;
2. yield the utterance and wait until it's done (i.e. the call to `speak()`);
3. suspend the thread;

In the case svox package is used, the relevant [snippet][2] forwards an RPC request to the speech device through a YARP port.

That said, I think it's likely that the problem is somehow with the speech device. To test this hypothesis, you could connect via RPC to the speechdev port in order to send your sentences and then note down if there is any discrepancy between the time instant when you'll actually hear the sound and the right moment when you'll get the response from the port.

[1]: https://github.com/robotology/speech/blob/master/iSpeak/main.cpp#L340-L350
[2]: https://github.com/robotology/speech/blob/master/iSpeak/main.cpp#L269-L272

**Comment by pattacini** [comment] 2017-05-15 13:21
Closing for the meantime.

**Closed** 2017-05-15 13:21 UTC
